---
services:
  backend:
    build: .
    ports:
      - "8087:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_APP=main.py
      - MAIL_SERVER=mailcatcher
      - MAIL_PORT=1025
      - MAIL_USE_TLS=False
      - MAIL_USE_SSL=False
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
    depends_on:
      - mailcatcher

  mailcatcher:
    image: sj26/mailcatcher:v0.10.0
    ports:
      - "1025:1025"  # SMTP port
      - "1088:1080"  # Web interface
