"""add_google_sheets_fields

Revision ID: 09eac370b337
Revises: 8d3e7b2a1c4f
Create Date: 2026-01-13 09:28:40.922591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09eac370b337'
down_revision = '8d3e7b2a1c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_sheets_link_honey', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('sheet_range_honey', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('google_sheets_link_lamm', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('sheet_range_lamm', sa.String(length=100), nullable=True))
        batch_op.drop_column('sheet_range')
        batch_op.drop_column('google_sheets_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_sheets_link', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('sheet_range', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('sheet_range_lamm')
        batch_op.drop_column('google_sheets_link_lamm')
        batch_op.drop_column('sheet_range_honey')
        batch_op.drop_column('google_sheets_link_honey')

    # ### end Alembic commands ###
