"""add_certificate_name

Revision ID: 671ba5ce2521
Revises: 70bff2bc0a1b
Create Date: 2025-12-30 19:13:55.180961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671ba5ce2521'
down_revision = '70bff2bc0a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_quantity', sa.Integer(), nullable=True))

    with op.batch_alter_table('bookings_lamm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings_lamm', schema=None) as batch_op:
        batch_op.drop_column('certificate_quantity')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('certificate_quantity')

    # ### end Alembic commands ###
