"""add_certificate_name

Revision ID: 70bff2bc0a1b
Revises: e1b73d902c36
Create Date: 2025-12-28 20:57:16.896047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70bff2bc0a1b'
down_revision = 'e1b73d902c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_invoices')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_name', sa.String(length=150), nullable=True))

    with op.batch_alter_table('bookings_lamm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_name', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings_lamm', schema=None) as batch_op:
        batch_op.drop_column('certificate_name')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('certificate_name')

    op.create_table('_alembic_tmp_invoices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('season_id', sa.INTEGER(), nullable=False),
    sa.Column('booking_id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('sent', sa.BOOLEAN(), nullable=True),
    sa.Column('date_payed', sa.DATETIME(), nullable=True),
    sa.Column('tot_sum', sa.FLOAT(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id')
    )
    # ### end Alembic commands ###
