"""add separate google sheets fields for honey and lamm to season

Revision ID: 8d3e7b2a1c4f
Revises: 671ba5ce2521
Create Date: 2026-01-13 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3e7b2a1c4f'
down_revision = '671ba5ce2521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_sheets_link_honey', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('sheet_range_honey', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('google_sheets_link_lamm', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('sheet_range_lamm', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_column('sheet_range_lamm')
        batch_op.drop_column('google_sheets_link_lamm')
        batch_op.drop_column('sheet_range_honey')
        batch_op.drop_column('google_sheets_link_honey')

    # ### end Alembic commands ###
